name: Proxies

on:
  workflow_dispatch:
#  schedule:
#    - cron: '3 2 * * *'

jobs:
  build:
    name: Proxy Pool
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GH_USERNAME }}
      EMAIL: ${{ secrets.GH_EMAIL }}
      MONTH: '05'

    steps:
      - uses: actions/checkout@v3
      - name: Download, Check and Renew
        if: always()
        run: |
          for i in $(seq -w 1 31); do
            wget -N https://github.com/pojiezhiyuanjun/freev2/raw/master/${{ env.MONTH }}$i.zip
            unzip ${{ env.MONTH }}$i.zip "*.txt" -d ./
            cat 节点.txt >> temp1
            rm -f 节点.txt ${{ env.MONTH }}$i.zip
          done
          
          wget -O ./vmessping_linux_$ARCH.tar.gz https://github.com/fscarmen/tools/releases/download/VMessPing/vmessping_linux_$ARCH.tar.gz
          tar -xzvf vmessping_linux_$ARCH.tar.gz
          
          dos2unix temp1
          sort -u temp1 | grep 'vmess://' > temp2
          
          CHECK=$($(cat temp2))
          for j in ${CHECK[@]}; do
           ./vmessping -allow-insecure -c 1 -o 1 $j && echo $j | tee -a ${GITHUB_WORKSPACE}/proxy
          done
          
      - name: Upload to REPO
        run: |
          git config --global user.email "${{ env.EMAIL }}"
          git config --global user.name "${{ env.USERNAME }}"
          git add .
          git commit -m "Update $(date "+%Y/%m/%d %H:%M:%S")"
          git push
